apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: health-ingress
  labels:
    app: health-ingress
spec:
  rules:
    - host: {{Environment.Host}}
      http:
        paths:
        - backend:
            serviceName: health-api-service
            servicePort: 80
